### ISSUE TITLE
Not finding versions for sites with potential updates

### ISSUE THREAD

**Issue by jjudish** [edgi-govdata-archiving/web-monitoring-versionista-scraper#195]
Hello,

I've been using this program once a week for about the past year with no issues.  Yesterday, the program ran, but returned no versions found.  I did a fresh git clone today, tried running it again, and got the same issue.  Did versionista change their website format or I am doing something wrong on my side?  Any help would be appreciated.  Below is the command I ran followed by the output.

>$ ~/web-monitoring-versionista-scraper/bin/scrape-versionista --email 'mysuperemail@gmail.com' --password mysuperpassword --after 3 --format csv --output './scrape/versions.csv' --save-content --save-diffs
Found 6 sites with potential updates
Found 8 pages with potential updates
No versions found for https://versionista.com/99974/8025183/
No versions found for https://versionista.com/99974/7922469/
No versions found for https://versionista.com/100691/8135628/
No versions found for https://versionista.com/99974/7921466/
No versions found for https://versionista.com/100692/7940381/
No versions found for https://versionista.com/102118/8013270/
No versions found for https://versionista.com/106110/8284856/
No versions found for https://versionista.com/112513/9080262/
Found 0 versions with updates
Completed in 58 seconds

The "No versions found for \<link\>" has never been in the output before.  Any pages with potential updates will return no versions found.

Thanks in advance for any help

**Comment by Mr0grog** [comment]
Hmmm, we haven’t been seeing any issues, but I’ll check our logs for this as soon as I get back to a computer tonight. That message should be output if a page actually has no versions at all (not just no versions in your time range). It’s uncommon, but can happen when you have active pages in Versionista and an old version has been dropped because you have too much stored on your account. Have you checked those pages in Versionista to see if what it’s logging is correct?

Your args look all good, but as a side note, are you actively using the CSV format? In case you weren’t aware, we now output a *lot* more useful data about each version in all the other formats. (CSV hasn’t updated because some stakeholders are tied to the original set of columns).

Thanks for flagging this!

**Comment by Mr0grog** [comment]
Also, you should feel free to hop on Slack for more real-time discussions: 
https://archivers-slack.herokuapp.com

Are you running this totally on your own or are you part of the Web Integrity Project? We haven’t really been publishing managed releases to NPM or doing changelogs since we weren’t aware anyone else was just using this!

**Comment by Mr0grog** [comment]
Hey @jjudish, I’ve taken a look and Versionista definitely made *massive* changes — there’s no content delivered in the actual page anymore. I’m working up a fix and should have one ready for you to test in a few hours.

On the plus side, it looks like Versionista is finally starting to grow something approaching an actual API. On the minus side, it’s totally undocumented and appears to only have an endpoint for the list of versions in a page. I’m better similar changes are coming soon for the list of sites and list of pages in a site, so I’m also adding code to fail harder with a clearer message when data is not present on those pages like we expect.

**Comment by Mr0grog** [comment]
I added a fix for this in #196. Feel free to give that a try and comment if you run into any issues.

**Comment by jjudish** [comment]
@Mr0grog ,
Thanks for getting back to me so quickly!  Your fix worked perfectly.  To answer some of your previous questions, I was running this for the Web Integrity Project.  I don't normally use CSV either, I just copied and pasted the first example in the readme while I was testing out the errors on my own.

Again, thanks for your help!

**Comment by Mr0grog** [comment]
👍 no problem! Just let me know if the branch with the fix works well for you. It’s a totally different way of grabbing the same data, so I’d like to make sure there’s no data in your account(s) that might trip over a snag in this new logic that our data doesn’t.
